/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as publicCartRouteImport } from './routes/(public)/cart'
import { Route as publicAccessoriesRouteImport } from './routes/(public)/accessories'
import { Route as privatePaymentRouteRouteImport } from './routes/(private)/payment/route'
import { Route as publicWomanIndexRouteImport } from './routes/(public)/woman/index'
import { Route as publicManIndexRouteImport } from './routes/(public)/man/index'
import { Route as publicWomanIdRouteImport } from './routes/(public)/woman/$id'
import { Route as publicManIdRouteImport } from './routes/(public)/man/$id'
import { Route as privatePaymentStepInitialRouteImport } from './routes/(private)/payment/step-initial'
import { Route as privatePaymentStep3RouteImport } from './routes/(private)/payment/step-3'
import { Route as privatePaymentStep2RouteImport } from './routes/(private)/payment/step-2'
import { Route as privatePaymentStep1RouteImport } from './routes/(private)/payment/step-1'

const AuthRouteImport = createFileRoute('/auth')()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const publicCartRoute = publicCartRouteImport.update({
  id: '/(public)/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAccessoriesRoute = publicAccessoriesRouteImport.update({
  id: '/(public)/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePaymentRouteRoute = privatePaymentRouteRouteImport.update({
  id: '/(private)/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const publicWomanIndexRoute = publicWomanIndexRouteImport.update({
  id: '/(public)/woman/',
  path: '/woman/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicManIndexRoute = publicManIndexRouteImport.update({
  id: '/(public)/man/',
  path: '/man/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicWomanIdRoute = publicWomanIdRouteImport.update({
  id: '/(public)/woman/$id',
  path: '/woman/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const publicManIdRoute = publicManIdRouteImport.update({
  id: '/(public)/man/$id',
  path: '/man/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePaymentStepInitialRoute =
  privatePaymentStepInitialRouteImport.update({
    id: '/step-initial',
    path: '/step-initial',
    getParentRoute: () => privatePaymentRouteRoute,
  } as any)
const privatePaymentStep3Route = privatePaymentStep3RouteImport.update({
  id: '/step-3',
  path: '/step-3',
  getParentRoute: () => privatePaymentRouteRoute,
} as any)
const privatePaymentStep2Route = privatePaymentStep2RouteImport.update({
  id: '/step-2',
  path: '/step-2',
  getParentRoute: () => privatePaymentRouteRoute,
} as any)
const privatePaymentStep1Route = privatePaymentStep1RouteImport.update({
  id: '/step-1',
  path: '/step-1',
  getParentRoute: () => privatePaymentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payment': typeof privatePaymentRouteRouteWithChildren
  '/accessories': typeof publicAccessoriesRoute
  '/cart': typeof publicCartRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/payment/step-1': typeof privatePaymentStep1Route
  '/payment/step-2': typeof privatePaymentStep2Route
  '/payment/step-3': typeof privatePaymentStep3Route
  '/payment/step-initial': typeof privatePaymentStepInitialRoute
  '/man/$id': typeof publicManIdRoute
  '/woman/$id': typeof publicWomanIdRoute
  '/man': typeof publicManIndexRoute
  '/woman': typeof publicWomanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payment': typeof privatePaymentRouteRouteWithChildren
  '/accessories': typeof publicAccessoriesRoute
  '/cart': typeof publicCartRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/payment/step-1': typeof privatePaymentStep1Route
  '/payment/step-2': typeof privatePaymentStep2Route
  '/payment/step-3': typeof privatePaymentStep3Route
  '/payment/step-initial': typeof privatePaymentStepInitialRoute
  '/man/$id': typeof publicManIdRoute
  '/woman/$id': typeof publicWomanIdRoute
  '/man': typeof publicManIndexRoute
  '/woman': typeof publicWomanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(private)/payment': typeof privatePaymentRouteRouteWithChildren
  '/(public)/accessories': typeof publicAccessoriesRoute
  '/(public)/cart': typeof publicCartRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/(private)/payment/step-1': typeof privatePaymentStep1Route
  '/(private)/payment/step-2': typeof privatePaymentStep2Route
  '/(private)/payment/step-3': typeof privatePaymentStep3Route
  '/(private)/payment/step-initial': typeof privatePaymentStepInitialRoute
  '/(public)/man/$id': typeof publicManIdRoute
  '/(public)/woman/$id': typeof publicWomanIdRoute
  '/(public)/man/': typeof publicManIndexRoute
  '/(public)/woman/': typeof publicWomanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payment'
    | '/accessories'
    | '/cart'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/payment/step-1'
    | '/payment/step-2'
    | '/payment/step-3'
    | '/payment/step-initial'
    | '/man/$id'
    | '/woman/$id'
    | '/man'
    | '/woman'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/payment'
    | '/accessories'
    | '/cart'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/payment/step-1'
    | '/payment/step-2'
    | '/payment/step-3'
    | '/payment/step-initial'
    | '/man/$id'
    | '/woman/$id'
    | '/man'
    | '/woman'
  id:
    | '__root__'
    | '/'
    | '/(private)/payment'
    | '/(public)/accessories'
    | '/(public)/cart'
    | '/auth'
    | '/auth/_layout'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/(private)/payment/step-1'
    | '/(private)/payment/step-2'
    | '/(private)/payment/step-3'
    | '/(private)/payment/step-initial'
    | '/(public)/man/$id'
    | '/(public)/woman/$id'
    | '/(public)/man/'
    | '/(public)/woman/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  privatePaymentRouteRoute: typeof privatePaymentRouteRouteWithChildren
  publicAccessoriesRoute: typeof publicAccessoriesRoute
  publicCartRoute: typeof publicCartRoute
  AuthRoute: typeof AuthRouteWithChildren
  publicManIdRoute: typeof publicManIdRoute
  publicWomanIdRoute: typeof publicWomanIdRoute
  publicManIndexRoute: typeof publicManIndexRoute
  publicWomanIndexRoute: typeof publicWomanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(public)/cart': {
      id: '/(public)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof publicCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/accessories': {
      id: '/(public)/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof publicAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/payment': {
      id: '/(private)/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof privatePaymentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/woman/': {
      id: '/(public)/woman/'
      path: '/woman'
      fullPath: '/woman'
      preLoaderRoute: typeof publicWomanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/man/': {
      id: '/(public)/man/'
      path: '/man'
      fullPath: '/man'
      preLoaderRoute: typeof publicManIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/woman/$id': {
      id: '/(public)/woman/$id'
      path: '/woman/$id'
      fullPath: '/woman/$id'
      preLoaderRoute: typeof publicWomanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/man/$id': {
      id: '/(public)/man/$id'
      path: '/man/$id'
      fullPath: '/man/$id'
      preLoaderRoute: typeof publicManIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/payment/step-initial': {
      id: '/(private)/payment/step-initial'
      path: '/step-initial'
      fullPath: '/payment/step-initial'
      preLoaderRoute: typeof privatePaymentStepInitialRouteImport
      parentRoute: typeof privatePaymentRouteRoute
    }
    '/(private)/payment/step-3': {
      id: '/(private)/payment/step-3'
      path: '/step-3'
      fullPath: '/payment/step-3'
      preLoaderRoute: typeof privatePaymentStep3RouteImport
      parentRoute: typeof privatePaymentRouteRoute
    }
    '/(private)/payment/step-2': {
      id: '/(private)/payment/step-2'
      path: '/step-2'
      fullPath: '/payment/step-2'
      preLoaderRoute: typeof privatePaymentStep2RouteImport
      parentRoute: typeof privatePaymentRouteRoute
    }
    '/(private)/payment/step-1': {
      id: '/(private)/payment/step-1'
      path: '/step-1'
      fullPath: '/payment/step-1'
      preLoaderRoute: typeof privatePaymentStep1RouteImport
      parentRoute: typeof privatePaymentRouteRoute
    }
  }
}

interface privatePaymentRouteRouteChildren {
  privatePaymentStep1Route: typeof privatePaymentStep1Route
  privatePaymentStep2Route: typeof privatePaymentStep2Route
  privatePaymentStep3Route: typeof privatePaymentStep3Route
  privatePaymentStepInitialRoute: typeof privatePaymentStepInitialRoute
}

const privatePaymentRouteRouteChildren: privatePaymentRouteRouteChildren = {
  privatePaymentStep1Route: privatePaymentStep1Route,
  privatePaymentStep2Route: privatePaymentStep2Route,
  privatePaymentStep3Route: privatePaymentStep3Route,
  privatePaymentStepInitialRoute: privatePaymentStepInitialRoute,
}

const privatePaymentRouteRouteWithChildren =
  privatePaymentRouteRoute._addFileChildren(privatePaymentRouteRouteChildren)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  privatePaymentRouteRoute: privatePaymentRouteRouteWithChildren,
  publicAccessoriesRoute: publicAccessoriesRoute,
  publicCartRoute: publicCartRoute,
  AuthRoute: AuthRouteWithChildren,
  publicManIdRoute: publicManIdRoute,
  publicWomanIdRoute: publicWomanIdRoute,
  publicManIndexRoute: publicManIndexRoute,
  publicWomanIndexRoute: publicWomanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
