/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as publicCartRouteImport } from './routes/(public)/cart'
import { Route as publicAccessoriesRouteImport } from './routes/(public)/accessories'
import { Route as publicManufacturerRouteRouteImport } from './routes/(public)/manufacturer/route'
import { Route as publicCustomizeRouteRouteImport } from './routes/(public)/customize/route'
import { Route as publicClientAreaRouteRouteImport } from './routes/(public)/client-area/route'
import { Route as privatePaymentRouteRouteImport } from './routes/(private)/payment/route'
import { Route as publicWomanIndexRouteImport } from './routes/(public)/woman/index'
import { Route as publicManIndexRouteImport } from './routes/(public)/man/index'
import { Route as privateCatalogIndexRouteImport } from './routes/(private)/catalog/index'
import { Route as publicWomanIdRouteImport } from './routes/(public)/woman/$id'
import { Route as publicManufacturerRegisteredRouteImport } from './routes/(public)/manufacturer/registered'
import { Route as publicManufacturerRegisterRouteImport } from './routes/(public)/manufacturer/register'
import { Route as publicManufacturerOnboardingRouteImport } from './routes/(public)/manufacturer/onboarding'
import { Route as publicManufacturerAccountAndTermsRouteImport } from './routes/(public)/manufacturer/account-and-terms'
import { Route as publicManIdRouteImport } from './routes/(public)/man/$id'
import { Route as publicCustomizeStep7RouteImport } from './routes/(public)/customize/step-7'
import { Route as publicCustomizeStep6RouteImport } from './routes/(public)/customize/step-6'
import { Route as publicCustomizeStep5RouteImport } from './routes/(public)/customize/step-5'
import { Route as publicCustomizeStep4RouteImport } from './routes/(public)/customize/step-4'
import { Route as publicCustomizeStep3RouteImport } from './routes/(public)/customize/step-3'
import { Route as publicCustomizeStep2RouteImport } from './routes/(public)/customize/step-2'
import { Route as publicCustomizeStep1RouteImport } from './routes/(public)/customize/step-1'
import { Route as publicClientAreaPurchaseHistoryRouteImport } from './routes/(public)/client-area/purchase-history'
import { Route as publicClientAreaProfileRouteImport } from './routes/(public)/client-area/profile'
import { Route as publicClientAreaNotificationsAndPreferencesRouteImport } from './routes/(public)/client-area/notifications-and-preferences'
import { Route as publicClientAreaMeasurementDataRouteImport } from './routes/(public)/client-area/measurement-data'
import { Route as publicClientAreaAppointmentsRouteImport } from './routes/(public)/client-area/appointments'
import { Route as privatePaymentStepInitialRouteImport } from './routes/(private)/payment/step-initial'
import { Route as privatePaymentStep3RouteImport } from './routes/(private)/payment/step-3'
import { Route as privatePaymentStep2RouteImport } from './routes/(private)/payment/step-2'
import { Route as privatePaymentStep1RouteImport } from './routes/(private)/payment/step-1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const publicCartRoute = publicCartRouteImport.update({
  id: '/(public)/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAccessoriesRoute = publicAccessoriesRouteImport.update({
  id: '/(public)/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const publicManufacturerRouteRoute = publicManufacturerRouteRouteImport.update({
  id: '/(public)/manufacturer',
  path: '/manufacturer',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCustomizeRouteRoute = publicCustomizeRouteRouteImport.update({
  id: '/(public)/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const publicClientAreaRouteRoute = publicClientAreaRouteRouteImport.update({
  id: '/(public)/client-area',
  path: '/client-area',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePaymentRouteRoute = privatePaymentRouteRouteImport.update({
  id: '/(private)/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const publicWomanIndexRoute = publicWomanIndexRouteImport.update({
  id: '/(public)/woman/',
  path: '/woman/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicManIndexRoute = publicManIndexRouteImport.update({
  id: '/(public)/man/',
  path: '/man/',
  getParentRoute: () => rootRouteImport,
} as any)
const privateCatalogIndexRoute = privateCatalogIndexRouteImport.update({
  id: '/(private)/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicWomanIdRoute = publicWomanIdRouteImport.update({
  id: '/(public)/woman/$id',
  path: '/woman/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const publicManufacturerRegisteredRoute =
  publicManufacturerRegisteredRouteImport.update({
    id: '/registered',
    path: '/registered',
    getParentRoute: () => publicManufacturerRouteRoute,
  } as any)
const publicManufacturerRegisterRoute =
  publicManufacturerRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => publicManufacturerRouteRoute,
  } as any)
const publicManufacturerOnboardingRoute =
  publicManufacturerOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => publicManufacturerRouteRoute,
  } as any)
const publicManufacturerAccountAndTermsRoute =
  publicManufacturerAccountAndTermsRouteImport.update({
    id: '/account-and-terms',
    path: '/account-and-terms',
    getParentRoute: () => publicManufacturerRouteRoute,
  } as any)
const publicManIdRoute = publicManIdRouteImport.update({
  id: '/(public)/man/$id',
  path: '/man/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCustomizeStep7Route = publicCustomizeStep7RouteImport.update({
  id: '/step-7',
  path: '/step-7',
  getParentRoute: () => publicCustomizeRouteRoute,
} as any)
const publicCustomizeStep6Route = publicCustomizeStep6RouteImport.update({
  id: '/step-6',
  path: '/step-6',
  getParentRoute: () => publicCustomizeRouteRoute,
} as any)
const publicCustomizeStep5Route = publicCustomizeStep5RouteImport.update({
  id: '/step-5',
  path: '/step-5',
  getParentRoute: () => publicCustomizeRouteRoute,
} as any)
const publicCustomizeStep4Route = publicCustomizeStep4RouteImport.update({
  id: '/step-4',
  path: '/step-4',
  getParentRoute: () => publicCustomizeRouteRoute,
} as any)
const publicCustomizeStep3Route = publicCustomizeStep3RouteImport.update({
  id: '/step-3',
  path: '/step-3',
  getParentRoute: () => publicCustomizeRouteRoute,
} as any)
const publicCustomizeStep2Route = publicCustomizeStep2RouteImport.update({
  id: '/step-2',
  path: '/step-2',
  getParentRoute: () => publicCustomizeRouteRoute,
} as any)
const publicCustomizeStep1Route = publicCustomizeStep1RouteImport.update({
  id: '/step-1',
  path: '/step-1',
  getParentRoute: () => publicCustomizeRouteRoute,
} as any)
const publicClientAreaPurchaseHistoryRoute =
  publicClientAreaPurchaseHistoryRouteImport.update({
    id: '/purchase-history',
    path: '/purchase-history',
    getParentRoute: () => publicClientAreaRouteRoute,
  } as any)
const publicClientAreaProfileRoute = publicClientAreaProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => publicClientAreaRouteRoute,
} as any)
const publicClientAreaNotificationsAndPreferencesRoute =
  publicClientAreaNotificationsAndPreferencesRouteImport.update({
    id: '/notifications-and-preferences',
    path: '/notifications-and-preferences',
    getParentRoute: () => publicClientAreaRouteRoute,
  } as any)
const publicClientAreaMeasurementDataRoute =
  publicClientAreaMeasurementDataRouteImport.update({
    id: '/measurement-data',
    path: '/measurement-data',
    getParentRoute: () => publicClientAreaRouteRoute,
  } as any)
const publicClientAreaAppointmentsRoute =
  publicClientAreaAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => publicClientAreaRouteRoute,
  } as any)
const privatePaymentStepInitialRoute =
  privatePaymentStepInitialRouteImport.update({
    id: '/step-initial',
    path: '/step-initial',
    getParentRoute: () => privatePaymentRouteRoute,
  } as any)
const privatePaymentStep3Route = privatePaymentStep3RouteImport.update({
  id: '/step-3',
  path: '/step-3',
  getParentRoute: () => privatePaymentRouteRoute,
} as any)
const privatePaymentStep2Route = privatePaymentStep2RouteImport.update({
  id: '/step-2',
  path: '/step-2',
  getParentRoute: () => privatePaymentRouteRoute,
} as any)
const privatePaymentStep1Route = privatePaymentStep1RouteImport.update({
  id: '/step-1',
  path: '/step-1',
  getParentRoute: () => privatePaymentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payment': typeof privatePaymentRouteRouteWithChildren
  '/client-area': typeof publicClientAreaRouteRouteWithChildren
  '/customize': typeof publicCustomizeRouteRouteWithChildren
  '/manufacturer': typeof publicManufacturerRouteRouteWithChildren
  '/accessories': typeof publicAccessoriesRoute
  '/cart': typeof publicCartRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/payment/step-1': typeof privatePaymentStep1Route
  '/payment/step-2': typeof privatePaymentStep2Route
  '/payment/step-3': typeof privatePaymentStep3Route
  '/payment/step-initial': typeof privatePaymentStepInitialRoute
  '/client-area/appointments': typeof publicClientAreaAppointmentsRoute
  '/client-area/measurement-data': typeof publicClientAreaMeasurementDataRoute
  '/client-area/notifications-and-preferences': typeof publicClientAreaNotificationsAndPreferencesRoute
  '/client-area/profile': typeof publicClientAreaProfileRoute
  '/client-area/purchase-history': typeof publicClientAreaPurchaseHistoryRoute
  '/customize/step-1': typeof publicCustomizeStep1Route
  '/customize/step-2': typeof publicCustomizeStep2Route
  '/customize/step-3': typeof publicCustomizeStep3Route
  '/customize/step-4': typeof publicCustomizeStep4Route
  '/customize/step-5': typeof publicCustomizeStep5Route
  '/customize/step-6': typeof publicCustomizeStep6Route
  '/customize/step-7': typeof publicCustomizeStep7Route
  '/man/$id': typeof publicManIdRoute
  '/manufacturer/account-and-terms': typeof publicManufacturerAccountAndTermsRoute
  '/manufacturer/onboarding': typeof publicManufacturerOnboardingRoute
  '/manufacturer/register': typeof publicManufacturerRegisterRoute
  '/manufacturer/registered': typeof publicManufacturerRegisteredRoute
  '/woman/$id': typeof publicWomanIdRoute
  '/catalog': typeof privateCatalogIndexRoute
  '/man': typeof publicManIndexRoute
  '/woman': typeof publicWomanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payment': typeof privatePaymentRouteRouteWithChildren
  '/client-area': typeof publicClientAreaRouteRouteWithChildren
  '/customize': typeof publicCustomizeRouteRouteWithChildren
  '/manufacturer': typeof publicManufacturerRouteRouteWithChildren
  '/accessories': typeof publicAccessoriesRoute
  '/cart': typeof publicCartRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/payment/step-1': typeof privatePaymentStep1Route
  '/payment/step-2': typeof privatePaymentStep2Route
  '/payment/step-3': typeof privatePaymentStep3Route
  '/payment/step-initial': typeof privatePaymentStepInitialRoute
  '/client-area/appointments': typeof publicClientAreaAppointmentsRoute
  '/client-area/measurement-data': typeof publicClientAreaMeasurementDataRoute
  '/client-area/notifications-and-preferences': typeof publicClientAreaNotificationsAndPreferencesRoute
  '/client-area/profile': typeof publicClientAreaProfileRoute
  '/client-area/purchase-history': typeof publicClientAreaPurchaseHistoryRoute
  '/customize/step-1': typeof publicCustomizeStep1Route
  '/customize/step-2': typeof publicCustomizeStep2Route
  '/customize/step-3': typeof publicCustomizeStep3Route
  '/customize/step-4': typeof publicCustomizeStep4Route
  '/customize/step-5': typeof publicCustomizeStep5Route
  '/customize/step-6': typeof publicCustomizeStep6Route
  '/customize/step-7': typeof publicCustomizeStep7Route
  '/man/$id': typeof publicManIdRoute
  '/manufacturer/account-and-terms': typeof publicManufacturerAccountAndTermsRoute
  '/manufacturer/onboarding': typeof publicManufacturerOnboardingRoute
  '/manufacturer/register': typeof publicManufacturerRegisterRoute
  '/manufacturer/registered': typeof publicManufacturerRegisteredRoute
  '/woman/$id': typeof publicWomanIdRoute
  '/catalog': typeof privateCatalogIndexRoute
  '/man': typeof publicManIndexRoute
  '/woman': typeof publicWomanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(private)/payment': typeof privatePaymentRouteRouteWithChildren
  '/(public)/client-area': typeof publicClientAreaRouteRouteWithChildren
  '/(public)/customize': typeof publicCustomizeRouteRouteWithChildren
  '/(public)/manufacturer': typeof publicManufacturerRouteRouteWithChildren
  '/(public)/accessories': typeof publicAccessoriesRoute
  '/(public)/cart': typeof publicCartRoute
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/(private)/payment/step-1': typeof privatePaymentStep1Route
  '/(private)/payment/step-2': typeof privatePaymentStep2Route
  '/(private)/payment/step-3': typeof privatePaymentStep3Route
  '/(private)/payment/step-initial': typeof privatePaymentStepInitialRoute
  '/(public)/client-area/appointments': typeof publicClientAreaAppointmentsRoute
  '/(public)/client-area/measurement-data': typeof publicClientAreaMeasurementDataRoute
  '/(public)/client-area/notifications-and-preferences': typeof publicClientAreaNotificationsAndPreferencesRoute
  '/(public)/client-area/profile': typeof publicClientAreaProfileRoute
  '/(public)/client-area/purchase-history': typeof publicClientAreaPurchaseHistoryRoute
  '/(public)/customize/step-1': typeof publicCustomizeStep1Route
  '/(public)/customize/step-2': typeof publicCustomizeStep2Route
  '/(public)/customize/step-3': typeof publicCustomizeStep3Route
  '/(public)/customize/step-4': typeof publicCustomizeStep4Route
  '/(public)/customize/step-5': typeof publicCustomizeStep5Route
  '/(public)/customize/step-6': typeof publicCustomizeStep6Route
  '/(public)/customize/step-7': typeof publicCustomizeStep7Route
  '/(public)/man/$id': typeof publicManIdRoute
  '/(public)/manufacturer/account-and-terms': typeof publicManufacturerAccountAndTermsRoute
  '/(public)/manufacturer/onboarding': typeof publicManufacturerOnboardingRoute
  '/(public)/manufacturer/register': typeof publicManufacturerRegisterRoute
  '/(public)/manufacturer/registered': typeof publicManufacturerRegisteredRoute
  '/(public)/woman/$id': typeof publicWomanIdRoute
  '/(private)/catalog/': typeof privateCatalogIndexRoute
  '/(public)/man/': typeof publicManIndexRoute
  '/(public)/woman/': typeof publicWomanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payment'
    | '/client-area'
    | '/customize'
    | '/manufacturer'
    | '/accessories'
    | '/cart'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/payment/step-1'
    | '/payment/step-2'
    | '/payment/step-3'
    | '/payment/step-initial'
    | '/client-area/appointments'
    | '/client-area/measurement-data'
    | '/client-area/notifications-and-preferences'
    | '/client-area/profile'
    | '/client-area/purchase-history'
    | '/customize/step-1'
    | '/customize/step-2'
    | '/customize/step-3'
    | '/customize/step-4'
    | '/customize/step-5'
    | '/customize/step-6'
    | '/customize/step-7'
    | '/man/$id'
    | '/manufacturer/account-and-terms'
    | '/manufacturer/onboarding'
    | '/manufacturer/register'
    | '/manufacturer/registered'
    | '/woman/$id'
    | '/catalog'
    | '/man'
    | '/woman'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/payment'
    | '/client-area'
    | '/customize'
    | '/manufacturer'
    | '/accessories'
    | '/cart'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/payment/step-1'
    | '/payment/step-2'
    | '/payment/step-3'
    | '/payment/step-initial'
    | '/client-area/appointments'
    | '/client-area/measurement-data'
    | '/client-area/notifications-and-preferences'
    | '/client-area/profile'
    | '/client-area/purchase-history'
    | '/customize/step-1'
    | '/customize/step-2'
    | '/customize/step-3'
    | '/customize/step-4'
    | '/customize/step-5'
    | '/customize/step-6'
    | '/customize/step-7'
    | '/man/$id'
    | '/manufacturer/account-and-terms'
    | '/manufacturer/onboarding'
    | '/manufacturer/register'
    | '/manufacturer/registered'
    | '/woman/$id'
    | '/catalog'
    | '/man'
    | '/woman'
  id:
    | '__root__'
    | '/'
    | '/(private)/payment'
    | '/(public)/client-area'
    | '/(public)/customize'
    | '/(public)/manufacturer'
    | '/(public)/accessories'
    | '/(public)/cart'
    | '/auth/_layout'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/(private)/payment/step-1'
    | '/(private)/payment/step-2'
    | '/(private)/payment/step-3'
    | '/(private)/payment/step-initial'
    | '/(public)/client-area/appointments'
    | '/(public)/client-area/measurement-data'
    | '/(public)/client-area/notifications-and-preferences'
    | '/(public)/client-area/profile'
    | '/(public)/client-area/purchase-history'
    | '/(public)/customize/step-1'
    | '/(public)/customize/step-2'
    | '/(public)/customize/step-3'
    | '/(public)/customize/step-4'
    | '/(public)/customize/step-5'
    | '/(public)/customize/step-6'
    | '/(public)/customize/step-7'
    | '/(public)/man/$id'
    | '/(public)/manufacturer/account-and-terms'
    | '/(public)/manufacturer/onboarding'
    | '/(public)/manufacturer/register'
    | '/(public)/manufacturer/registered'
    | '/(public)/woman/$id'
    | '/(private)/catalog/'
    | '/(public)/man/'
    | '/(public)/woman/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  privatePaymentRouteRoute: typeof privatePaymentRouteRouteWithChildren
  publicClientAreaRouteRoute: typeof publicClientAreaRouteRouteWithChildren
  publicCustomizeRouteRoute: typeof publicCustomizeRouteRouteWithChildren
  publicManufacturerRouteRoute: typeof publicManufacturerRouteRouteWithChildren
  publicAccessoriesRoute: typeof publicAccessoriesRoute
  publicCartRoute: typeof publicCartRoute
  publicManIdRoute: typeof publicManIdRoute
  publicWomanIdRoute: typeof publicWomanIdRoute
  privateCatalogIndexRoute: typeof privateCatalogIndexRoute
  publicManIndexRoute: typeof publicManIndexRoute
  publicWomanIndexRoute: typeof publicWomanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: ''
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(public)/cart': {
      id: '/(public)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof publicCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/accessories': {
      id: '/(public)/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof publicAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/manufacturer': {
      id: '/(public)/manufacturer'
      path: '/manufacturer'
      fullPath: '/manufacturer'
      preLoaderRoute: typeof publicManufacturerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/customize': {
      id: '/(public)/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof publicCustomizeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/client-area': {
      id: '/(public)/client-area'
      path: '/client-area'
      fullPath: '/client-area'
      preLoaderRoute: typeof publicClientAreaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/payment': {
      id: '/(private)/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof privatePaymentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/woman/': {
      id: '/(public)/woman/'
      path: '/woman'
      fullPath: '/woman'
      preLoaderRoute: typeof publicWomanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/man/': {
      id: '/(public)/man/'
      path: '/man'
      fullPath: '/man'
      preLoaderRoute: typeof publicManIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/catalog/': {
      id: '/(private)/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof privateCatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/woman/$id': {
      id: '/(public)/woman/$id'
      path: '/woman/$id'
      fullPath: '/woman/$id'
      preLoaderRoute: typeof publicWomanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/manufacturer/registered': {
      id: '/(public)/manufacturer/registered'
      path: '/registered'
      fullPath: '/manufacturer/registered'
      preLoaderRoute: typeof publicManufacturerRegisteredRouteImport
      parentRoute: typeof publicManufacturerRouteRoute
    }
    '/(public)/manufacturer/register': {
      id: '/(public)/manufacturer/register'
      path: '/register'
      fullPath: '/manufacturer/register'
      preLoaderRoute: typeof publicManufacturerRegisterRouteImport
      parentRoute: typeof publicManufacturerRouteRoute
    }
    '/(public)/manufacturer/onboarding': {
      id: '/(public)/manufacturer/onboarding'
      path: '/onboarding'
      fullPath: '/manufacturer/onboarding'
      preLoaderRoute: typeof publicManufacturerOnboardingRouteImport
      parentRoute: typeof publicManufacturerRouteRoute
    }
    '/(public)/manufacturer/account-and-terms': {
      id: '/(public)/manufacturer/account-and-terms'
      path: '/account-and-terms'
      fullPath: '/manufacturer/account-and-terms'
      preLoaderRoute: typeof publicManufacturerAccountAndTermsRouteImport
      parentRoute: typeof publicManufacturerRouteRoute
    }
    '/(public)/man/$id': {
      id: '/(public)/man/$id'
      path: '/man/$id'
      fullPath: '/man/$id'
      preLoaderRoute: typeof publicManIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/customize/step-7': {
      id: '/(public)/customize/step-7'
      path: '/step-7'
      fullPath: '/customize/step-7'
      preLoaderRoute: typeof publicCustomizeStep7RouteImport
      parentRoute: typeof publicCustomizeRouteRoute
    }
    '/(public)/customize/step-6': {
      id: '/(public)/customize/step-6'
      path: '/step-6'
      fullPath: '/customize/step-6'
      preLoaderRoute: typeof publicCustomizeStep6RouteImport
      parentRoute: typeof publicCustomizeRouteRoute
    }
    '/(public)/customize/step-5': {
      id: '/(public)/customize/step-5'
      path: '/step-5'
      fullPath: '/customize/step-5'
      preLoaderRoute: typeof publicCustomizeStep5RouteImport
      parentRoute: typeof publicCustomizeRouteRoute
    }
    '/(public)/customize/step-4': {
      id: '/(public)/customize/step-4'
      path: '/step-4'
      fullPath: '/customize/step-4'
      preLoaderRoute: typeof publicCustomizeStep4RouteImport
      parentRoute: typeof publicCustomizeRouteRoute
    }
    '/(public)/customize/step-3': {
      id: '/(public)/customize/step-3'
      path: '/step-3'
      fullPath: '/customize/step-3'
      preLoaderRoute: typeof publicCustomizeStep3RouteImport
      parentRoute: typeof publicCustomizeRouteRoute
    }
    '/(public)/customize/step-2': {
      id: '/(public)/customize/step-2'
      path: '/step-2'
      fullPath: '/customize/step-2'
      preLoaderRoute: typeof publicCustomizeStep2RouteImport
      parentRoute: typeof publicCustomizeRouteRoute
    }
    '/(public)/customize/step-1': {
      id: '/(public)/customize/step-1'
      path: '/step-1'
      fullPath: '/customize/step-1'
      preLoaderRoute: typeof publicCustomizeStep1RouteImport
      parentRoute: typeof publicCustomizeRouteRoute
    }
    '/(public)/client-area/purchase-history': {
      id: '/(public)/client-area/purchase-history'
      path: '/purchase-history'
      fullPath: '/client-area/purchase-history'
      preLoaderRoute: typeof publicClientAreaPurchaseHistoryRouteImport
      parentRoute: typeof publicClientAreaRouteRoute
    }
    '/(public)/client-area/profile': {
      id: '/(public)/client-area/profile'
      path: '/profile'
      fullPath: '/client-area/profile'
      preLoaderRoute: typeof publicClientAreaProfileRouteImport
      parentRoute: typeof publicClientAreaRouteRoute
    }
    '/(public)/client-area/notifications-and-preferences': {
      id: '/(public)/client-area/notifications-and-preferences'
      path: '/notifications-and-preferences'
      fullPath: '/client-area/notifications-and-preferences'
      preLoaderRoute: typeof publicClientAreaNotificationsAndPreferencesRouteImport
      parentRoute: typeof publicClientAreaRouteRoute
    }
    '/(public)/client-area/measurement-data': {
      id: '/(public)/client-area/measurement-data'
      path: '/measurement-data'
      fullPath: '/client-area/measurement-data'
      preLoaderRoute: typeof publicClientAreaMeasurementDataRouteImport
      parentRoute: typeof publicClientAreaRouteRoute
    }
    '/(public)/client-area/appointments': {
      id: '/(public)/client-area/appointments'
      path: '/appointments'
      fullPath: '/client-area/appointments'
      preLoaderRoute: typeof publicClientAreaAppointmentsRouteImport
      parentRoute: typeof publicClientAreaRouteRoute
    }
    '/(private)/payment/step-initial': {
      id: '/(private)/payment/step-initial'
      path: '/step-initial'
      fullPath: '/payment/step-initial'
      preLoaderRoute: typeof privatePaymentStepInitialRouteImport
      parentRoute: typeof privatePaymentRouteRoute
    }
    '/(private)/payment/step-3': {
      id: '/(private)/payment/step-3'
      path: '/step-3'
      fullPath: '/payment/step-3'
      preLoaderRoute: typeof privatePaymentStep3RouteImport
      parentRoute: typeof privatePaymentRouteRoute
    }
    '/(private)/payment/step-2': {
      id: '/(private)/payment/step-2'
      path: '/step-2'
      fullPath: '/payment/step-2'
      preLoaderRoute: typeof privatePaymentStep2RouteImport
      parentRoute: typeof privatePaymentRouteRoute
    }
    '/(private)/payment/step-1': {
      id: '/(private)/payment/step-1'
      path: '/step-1'
      fullPath: '/payment/step-1'
      preLoaderRoute: typeof privatePaymentStep1RouteImport
      parentRoute: typeof privatePaymentRouteRoute
    }
  }
}

interface privatePaymentRouteRouteChildren {
  privatePaymentStep1Route: typeof privatePaymentStep1Route
  privatePaymentStep2Route: typeof privatePaymentStep2Route
  privatePaymentStep3Route: typeof privatePaymentStep3Route
  privatePaymentStepInitialRoute: typeof privatePaymentStepInitialRoute
}

const privatePaymentRouteRouteChildren: privatePaymentRouteRouteChildren = {
  privatePaymentStep1Route: privatePaymentStep1Route,
  privatePaymentStep2Route: privatePaymentStep2Route,
  privatePaymentStep3Route: privatePaymentStep3Route,
  privatePaymentStepInitialRoute: privatePaymentStepInitialRoute,
}

const privatePaymentRouteRouteWithChildren =
  privatePaymentRouteRoute._addFileChildren(privatePaymentRouteRouteChildren)

interface publicClientAreaRouteRouteChildren {
  publicClientAreaAppointmentsRoute: typeof publicClientAreaAppointmentsRoute
  publicClientAreaMeasurementDataRoute: typeof publicClientAreaMeasurementDataRoute
  publicClientAreaNotificationsAndPreferencesRoute: typeof publicClientAreaNotificationsAndPreferencesRoute
  publicClientAreaProfileRoute: typeof publicClientAreaProfileRoute
  publicClientAreaPurchaseHistoryRoute: typeof publicClientAreaPurchaseHistoryRoute
}

const publicClientAreaRouteRouteChildren: publicClientAreaRouteRouteChildren = {
  publicClientAreaAppointmentsRoute: publicClientAreaAppointmentsRoute,
  publicClientAreaMeasurementDataRoute: publicClientAreaMeasurementDataRoute,
  publicClientAreaNotificationsAndPreferencesRoute:
    publicClientAreaNotificationsAndPreferencesRoute,
  publicClientAreaProfileRoute: publicClientAreaProfileRoute,
  publicClientAreaPurchaseHistoryRoute: publicClientAreaPurchaseHistoryRoute,
}

const publicClientAreaRouteRouteWithChildren =
  publicClientAreaRouteRoute._addFileChildren(
    publicClientAreaRouteRouteChildren,
  )

interface publicCustomizeRouteRouteChildren {
  publicCustomizeStep1Route: typeof publicCustomizeStep1Route
  publicCustomizeStep2Route: typeof publicCustomizeStep2Route
  publicCustomizeStep3Route: typeof publicCustomizeStep3Route
  publicCustomizeStep4Route: typeof publicCustomizeStep4Route
  publicCustomizeStep5Route: typeof publicCustomizeStep5Route
  publicCustomizeStep6Route: typeof publicCustomizeStep6Route
  publicCustomizeStep7Route: typeof publicCustomizeStep7Route
}

const publicCustomizeRouteRouteChildren: publicCustomizeRouteRouteChildren = {
  publicCustomizeStep1Route: publicCustomizeStep1Route,
  publicCustomizeStep2Route: publicCustomizeStep2Route,
  publicCustomizeStep3Route: publicCustomizeStep3Route,
  publicCustomizeStep4Route: publicCustomizeStep4Route,
  publicCustomizeStep5Route: publicCustomizeStep5Route,
  publicCustomizeStep6Route: publicCustomizeStep6Route,
  publicCustomizeStep7Route: publicCustomizeStep7Route,
}

const publicCustomizeRouteRouteWithChildren =
  publicCustomizeRouteRoute._addFileChildren(publicCustomizeRouteRouteChildren)

interface publicManufacturerRouteRouteChildren {
  publicManufacturerAccountAndTermsRoute: typeof publicManufacturerAccountAndTermsRoute
  publicManufacturerOnboardingRoute: typeof publicManufacturerOnboardingRoute
  publicManufacturerRegisterRoute: typeof publicManufacturerRegisterRoute
  publicManufacturerRegisteredRoute: typeof publicManufacturerRegisteredRoute
}

const publicManufacturerRouteRouteChildren: publicManufacturerRouteRouteChildren =
  {
    publicManufacturerAccountAndTermsRoute:
      publicManufacturerAccountAndTermsRoute,
    publicManufacturerOnboardingRoute: publicManufacturerOnboardingRoute,
    publicManufacturerRegisterRoute: publicManufacturerRegisterRoute,
    publicManufacturerRegisteredRoute: publicManufacturerRegisteredRoute,
  }

const publicManufacturerRouteRouteWithChildren =
  publicManufacturerRouteRoute._addFileChildren(
    publicManufacturerRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  privatePaymentRouteRoute: privatePaymentRouteRouteWithChildren,
  publicClientAreaRouteRoute: publicClientAreaRouteRouteWithChildren,
  publicCustomizeRouteRoute: publicCustomizeRouteRouteWithChildren,
  publicManufacturerRouteRoute: publicManufacturerRouteRouteWithChildren,
  publicAccessoriesRoute: publicAccessoriesRoute,
  publicCartRoute: publicCartRoute,
  publicManIdRoute: publicManIdRoute,
  publicWomanIdRoute: publicWomanIdRoute,
  privateCatalogIndexRoute: privateCatalogIndexRoute,
  publicManIndexRoute: publicManIndexRoute,
  publicWomanIndexRoute: publicWomanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
